/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package random.bot;

import javax.annotation.Nullable;

@Nullable
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
